# Generated by Django 3.1.4 on 2020-12-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cmimi', models.SmallIntegerField()),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
