# Generated by Django 3.1.5 on 2021-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=100)),
                ('cmimi', models.SmallIntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
